### ISSUE TITLE
AttributeError: module 'smaclite.env.rvo2.rvo2' has no attribute 'PyRVOSimulator'

### ISSUE THREAD

**Issue by JonasWild** [uoe-agents/smaclite#2]
Nowhere in the project PyRVOSimulator is defined. Thanks

**Comment by micadam** [comment]
I just realized that `example.py` has this flag set, which might be a bit counter-intuitive. I will edit this shortly.

**Comment by JonasWild** [comment]
Thanks for the fast response. Without the C++ version everything works optimally. I think I will just work with this configuration. Thanks!

**Comment by micadam** [comment]
Thanks, good to know it works now. I do recommend the C++ optional dependency as it makes the environment much faster, but both should be functionally the same. Closing the issue.
